a, b = input().split()
r1 = int(a) + int(b)
r2 = int(a) - int(b)
r3 = int(a) * int(b)
r4 = int(a) // int(b)
r5 = int(a) % int(b)
r6 = int(a) / int(b)
print(r1)
print(r2)
print(r3)
print(r4)
print(r5)
print(format(r6, ".2f"))